version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=duacodersdb
      - MYSQL_USER=duacoder
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    container_name: duacodersdb
  

volumes:
  my-db: